# Site settings

title: jtc
email: jtcohen6

description: Website of Jeremy T. Cohen, real person.

baseurl: "" #subpath
url: "http://jtcohen6.github.io" # base hostname & protocol for your site

twitter_username: "jtcohen6"
github_username: jtcohen6
linkedin_username: jeremytcohen
# instagram_username: jtcocopuffs

# Build settings

markdown: kramdown
