# Welcome to Jekyll!

#

# This config file is meant for settings that affect your whole blog, values

# which you are expected to set up once and rarely need to edit after that.

# For technical reasons, this file is *NOT* reloaded automatically when you use

# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings

title: JTC
email: jerco at sas dot upenn dot edu

description: Personal website of Jeremy T. Cohen, Classics & Statistics at the University of Pennsylvania.
# this means to ignore newlines until "baseurl:"

baseurl: "/" #subpath
url: "http://jtcohen6.github.io" # base hostname & protocol for your site

twitter_username: "jtcohen6"
github_username: jtcohen6

# Build settings

markdown: kramdown
